name: beast_locator
description: "Flutter port of BeastLocator."
publish_to: 'none' 

version: 0.9.5+20

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  flutter_compass: ^0.8.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  live_activities: ^2.4.9
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/yjsnpi.png
    - assets/images/icon.png
    - assets/audio/arrival_0km.wav
    - assets/audio/distance_114514km.mp3
    - assets/audio/distance_interval_kankaku.mp3

